[package]
name = "starkpulse_contract"
version = "0.1.0"
edition = "2023_01"
cairo-version = "2.9.2"

[dependencies]
starknet = "2.9.2"

[dev-dependencies]
cairo_test = "2.9.2"

[[target.starknet-contract]]
sierra = true
casm = true

[scripts]
test = "scarb cairo-test"